### ISSUE TITLE
include guard identifiers not compliant with SEI CERT C "standard"?

### ISSUE THREAD

**Issue by elfring** [libyal/libcerror#8]
I would like to point out that identifiers like “[`_FILE_STREAM_H `](https://github.com/libyal/libcerror/blob/3367ce13d37cd1dd8ffac8f48cd9a4afa0866a85/common/file_stream.h#L22 "Update candidate")” and “[`_LIBCERROR_H `](https://github.com/libyal/libcerror/blob/3367ce13d37cd1dd8ffac8f48cd9a4afa0866a85/include/libcerror.h.in#L22 "Another update candidate")” [do eventually not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier "Do not use identifiers which are reserved for the compiler implementation.") to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by joachimmetz** [comment]
Which C standard version?

**Comment by joachimmetz** [comment]
> Would you like to adjust your selection for unique names?

I can have a look, so far as I know, this has not caused issues yet

**Comment by elfring** [comment]
How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoiding undefined behaviour?")?

**Comment by joachimmetz** [comment]
@elfring could you please answer my questions on the second comment.

* I need to understand how these "recommendations" will impact compatibility with various compilers and versions.
* If there is tooling that can help "lint" for compliance issues

**Comment by joachimmetz** [comment]
> How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106)?

@elfring I don't understand what you are asking me, since there are factors outside the control of "this software" there will always be undefined behavior. You'll have to be more specific to what you are referencing?

**Comment by elfring** [comment]
* I am pointing out for a while to reconsider the tampering with [the reserved name space](https://en.cppreference.com/w/c/language/identifier#Reserved_identifiers "Description for reserved identifiers").
* Would you like to restrict [the safe usage of this software library](https://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier#answer-228797 "What are the rules about using an underscore in a C++ identifier?") for the implementation of compilers for the programming languages “C” and “C++”?

-----

Will it be sufficient (or safer) to delete leading underscores from affected include guards?

**Comment by joachimmetz** [comment]
> I am pointing out for a while to reconsider the tampering with [the reserved name space](https://en.cppreference.com/w/c/language/identifier#Reserved_identifiers).

I understand the issue you are pointing out.

What I'm asking you is **how this will "impact compatibility with various compilers and versions."**.

Since you are proposing the change and the documents you refer to do not provide such an assessment.

> Would you like to restrict [the safe usage of this software library](https://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier#answer-228797) for the implementation of compilers for the programming languages “C” and “C++”?

This largely reads as a C++ reference to me.

Also the recommendation does address the root of the problem. I only prevents re-use of a specific subset of "include guard identifiers". With or without the leading underscore, duplicate "include guard identifiers" can still exist. What makes more sense to me if a pre-compilation check would flag duplicated "include guard identifiers".

also "safe" here is highly subjective terminology.

**Comment by elfring** [comment]
* I suggest to take another look at linked information sources.
* Include guards can be constructed in a way so that they are reasonably unique without the usage of reserved identifiers.

**Comment by joachimmetz** [comment]
> I suggest to take another look at linked information sources.

Can you please answer my questions instead of evading them with such statements. Realize that this method of communication is demotivating me to consider making changes.

**Comment by elfring** [comment]
Why have you got difficulties with the understanding of the mentioned implementation detail for the relevance of standard compliance?

**Comment by joachimmetz** [comment]
> Why have you got difficulties with the understanding of the mentioned implementation detail for the relevance of standard compliance?

Because the "standard" you are referring to, even claims itself not to be a standard

The C rules and **recommendations** in this wiki are a **work in progress** and reflect the current thinking of the secure coding community.

**Comment by elfring** [comment]
* You seem to misinterpret und take a bit of information not so into account as intended.
* If you do not trust wiki documents, you would need to [read the section “6.4.2 Identifiers”](http://www.knosof.co.uk/cbook/ "C Language Book Material") from an official document for a standard like “ISO/IEC 9899:1999” again.

**Comment by joachimmetz** [comment]
To be verbose http://www.knosof.co.uk/cbook/ does not have a 'section “6.4.2 Identifiers”'. Assuming that you meant: http://www.coding-guidelines.com/cbook/c90c++.pdf 'section “6.4.2 Identifiers”' 

The only reference to underscore in this paragraph is 
```
93 An identifier is a sequence of nondigit characters (including the underscore _, the lowercase and uppercase Latin letters, and other characters) and digits, which designates one or more entities as described in 6.2.1.
````

So it is unclear to me why you are referencing this section in light of the include guards.

There is no reference to "include guard" or "header guard" in http://www.coding-guidelines.com/cbook/c90c++.pdf

Why can't you just point me to the exact standards document and paragraph?

**Comment by joachimmetz** [comment]
Section "6.4.2.2 Predefined identifiers" http://www.coding-guidelines.com/cbook/c90c++.pdf

```Names beginning with two underscores were specified as reserved for any use by the C90 Standard. The following program is likely to behave differently when translated and executed by a C99 implementation.```

And "likely to behave differently when translated and executed" is exactly what I'm asking you an assessment about.

**Comment by elfring** [comment]
Is the wording in recent standard specifications more precise than the mentioned information from C90?

**Comment by joachimmetz** [comment]
If you keep repeating question with more questions and continue to be unspecific. I have to conclude that this is not worth my time.

**Comment by elfring** [comment]
* You seem to exclude relevant information from publicly available documentation.
* I would appreciate if [undefined software behaviour could be prevented](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoidance of undefined behaviour") in more use cases.

**Comment by joachimmetz** [comment]
> You seem to exclude relevant information from publicly available documentation.

documentation that do not appear to be authoritative, nor have you pointed me to the authoritative documentation after multiple explicit requests to do so.  

> I would appreciate if [undefined software behaviour could be prevented](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106) in more use cases.

And I would appreciate for you to answer my questions I've asked you about this.

**Comment by elfring** [comment]
The non-authoritative documents provide references (also for the discussed detail) according to the official standard specifications, don't they?

**Comment by joachimmetz** [comment]
You are answering with a question again. WTF do you want, to argue or to get this addressed? If the latter than answer my questions.

**Comment by elfring** [comment]
It seems that you would need a printed copy of an official standard version to be sure.
Why do you expect a repetition of a standard wording after it was repeated so many times in various information systems already?

**Comment by joachimmetz** [comment]
Why are you so hung up about the standard? What I'm asking you:

* I need to understand how these "recommendations" will impact compatibility with various compilers and versions.
* If there is tooling that can help "lint" for compliance issues
* How this conflicts with other C standards

**Comment by elfring** [comment]
* I propose to take software development concerns better into account for standard compliance.
* The secure coding recommendations point software improvement possibilities out.
* Several tools can help you for this purpose. - You can choose.
* A specific coding style can trigger unwanted conflicts when users of such a software library apply it in special applications.

**Comment by joachimmetz** [comment]
@elfring you are not helpful, since you are unable to provide me with solutions and clear answer to my question

Since the practical impact is low (as indicated by SEI CERT C reference) expect this to be a low/none priority for me.

**Comment by elfring** [comment]
>…, since you are unable to provide me with solutions …

I proposed a possible renaming of affected identifiers.

**Comment by joachimmetz** [comment]
> I proposed a possible renaming of affected identifiers.

You have not even done that, read your comments.
"Would you like to adjust your selection for unique names?"

You might think that is what you are suggestion, but that is not how is comes across.

**Comment by elfring** [comment]
The involved software developers can choose which identifier selection would be more appropriate (and safer) finally.
